# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-18 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
