# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-19 06:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0003_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='fk_submission',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='key',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='package.Submission'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='package',
            name='fk_form',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='submission',
            name='fk',
            field=models.IntegerField(),
        ),
    ]
